---
# Source: forecastle/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: forecastle
    group: com.stakater.platform
    provider: stakater
    version: "v1.0.64"
    chart: "forecastle-v1.0.64"
    release: "forecastle"
    heritage: "Tiller"
  name: forecastle
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: forecastle-cluster-ingress-role
  labels:
    app: forecastle
    group: com.stakater.platform
    provider: stakater
    version: "v1.0.64"
    chart: "forecastle-v1.0.64"
    release: "forecastle"
    heritage: "Tiller"
rules:
- apiGroups: ["", "route.openshift.io", "extensions"]
  resources: ["ingresses", "routes", "namespaces"]
  verbs: ["get", "list"]
- apiGroups:
  - forecastle.stakater.com
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: forecastle-cluster-ingress-role-binding
  labels:
    app: forecastle
    group: com.stakater.platform
    provider: stakater
    version: "v1.0.64"
    chart: "forecastle-v1.0.64"
    release: "forecastle"
    heritage: "Tiller"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: forecastle-cluster-ingress-role
subjects:
- kind: ServiceAccount
  name: forecastle
  namespace: default

